# Packages I want on a graphical workstation.
gui_pkgs:
  - adobe-source-code-pro-fonts
  - emacs-gtk+x11 # pgtk doesn't work well in WSL2, even though it's Wayland?
  - emacs-notmuch
#  - emacs-pgtk
  - ibm-plex-mono-fonts
  - libvterm # for vterm in emacs
  - libvterm-devel
  - cmake # for emacs-vterm's install process

# Packages needed for my typical kernel development activities,
# derived from "dnf builddep kernel" with some editing.
kernel_dev_pkgs:
  - asciidoc
  - bash
  - bc
  - binutils
  - bison
  - bzip2
  - clang
  - coreutils
  - diffutils
  - dwarves
  - elfutils
  - findutils
  - flex
  - gawk
  - gcc
  - git-core
  - hostname
  - lld
  - llvm
  - m4
  - make
  - ncurses-devel
  - newt-devel
  - openssl
  - openssl-devel
  - perl-interpreter
  - pesign
  - python3
  - tar
  - which
  - xz
  - zstd

# Other things I would conceivably need on a headless/remote system.
cli_pkgs:
  - ccache
  - chezmoi
  - clang-tools-extra # for clangd
  - git-email
  - msmtp
  - ncdu
  - pipx # for b4 and afew
  - procps-ng
  - tmux
