---
# Packages installed on ALL hosts
base_packages:
  - gcc
  - clang
  - make
  - tmux
  - ncdu
  - chezmoi
  - git

username: nathanl

# User configuration
dev_user:
  name: "{{ username }}"
  groups:
    - wheel
    - kvm
  shell: /bin/bash
  ssh_key_type: ed25519
  ssh_key_comment: "{{ username }}@{{ ansible_hostname }}"
