---
# Packages installed on ALL hosts
base_packages:
  - gcc
  - clang
  - make
  - tmux
  - ncdu
  - chezmoi
  - git

login: nathanl
name: "Nathan Lynch"

# User configuration
dev_user:
  login: "{{ login }}"
  name: "{{ name }}"
  groups:
    - wheel
    - kvm
  shell: /bin/bash
  ssh_key_type: ed25519
  ssh_key_comment: "{{ name }}@{{ ansible_hostname }}"
