---
login: nathanl
realname: "Nathan Lynch"

# User configuration
dev_user:
  login: "{{ login }}"
  name: "{{ realname }}"
  groups:
    - wheel
    - kvm
  shell: /bin/bash
  ssh_key_type: ed25519
  ssh_key_comment: "{{ login }}@{{ ansible_hostname }}"
